Wow, so much wow. Random fix for uid/gid failure
https://travis-ci.com/hanneskaeufler/e-ink-build-dashboard/builds/141655209
The docker build failed due to the error below. Googling for this seems
to show a weird reason I dont want to get into. SO shows us how to
"fix" it: https://stackoverflow.com/a/52196681/1777136

Step 4/5 : RUN npm install --global https://github.com/mapbox/pixelmatch
234 ---> Running in 4cf2dcd8bd6e
235Error: could not get uid/gid
236[ 'nobody', 0 ]
237
238    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
239    at ChildProcess.exithandler (child_process.js:301:5)
240    at ChildProcess.emit (events.js:182:13)
241    at maybeClose (internal/child_process.js:962:16)
242    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
243TypeError: Cannot read property 'get' of undefined
244    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
245    at /usr/lib/node_modules/npm/bin/npm-cli.js:78:20
246    at cb (/usr/lib/node_modules/npm/lib/npm.js:228:22)
247    at /usr/lib/node_modules/npm/lib/npm.js:266:24
248    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
249    at Array.forEach (<anonymous>)
250    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
251    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
252    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
253    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:231:22)
254/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
255  if (npm.config.get('json')) {
256                 ^
257
258TypeError: Cannot read property 'get' of undefined
259    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
260    at process.emit (events.js:182:13)
261    at process._fatalException (internal/bootstrap/node.js:493:27)
262The command '/bin/sh -c npm install --global https://github.com/mapbox/pixelmatch' returned a non-zero code: 7
263Makefile:16: recipe for target 'build-dev' failed
264make: *** [build-dev] Error 7
265The command "make build-dev" exited with 2.